# Generated by Django 5.2.3 on 2025-08-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('limitMin', models.IntegerField(unique=True)),
                ('limitMax', models.IntegerField(unique=True)),
                ('departament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inventoryClass', to='creare_pv.departaments')),
            ],
        ),
        migrations.AddField(
            model_name='departaments',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='department', to='creare_pv.locations'),
        ),
        migrations.CreateModel(
            name='DepartmentObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='object', to='creare_pv.departaments')),
                ('objectType', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='object', to='creare_pv.objecttypes')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('departament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='person', to='creare_pv.departaments')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invNumber', models.PositiveBigIntegerField(unique=True)),
                ('description', models.CharField(max_length=100)),
                ('serialNumber', models.CharField(max_length=200)),
                ('imei', models.CharField(max_length=18)),
                ('observations', models.CharField(blank=True, max_length=256, null=True)),
                ('departament', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='asset', to='creare_pv.departaments')),
                ('inventoryClass', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='asset', to='creare_pv.inventoryclasses')),
                ('objectType', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='asset', to='creare_pv.objecttypes')),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='asset', to='creare_pv.persons')),
            ],
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvType', models.CharField(max_length=10)),
                ('nrTicket', models.CharField(max_length=10)),
                ('invNumber', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pv', to='creare_pv.assets')),
                ('recipient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipient', to='creare_pv.persons')),
                ('reqester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requester', to='creare_pv.persons')),
            ],
        ),
    ]
