# Generated by Django 5.2.3 on 2025-06-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_type', models.CharField(choices=[('PRIMIRE', 'primire'), ('PREDARE', 'predare')], default='PRIMIRE', help_text='Selectati daca este un proces verbal de primire sau de predare.', max_length=10)),
                ('pers1_addressing', models.CharField(choices=[('Dl', 'Dl'), ('Dna', 'Dna')], default='Dl', max_length=5)),
                ('pers1_name', models.CharField(max_length=50)),
                ('pers2_addressing', models.CharField(choices=[('Dl', 'Dl'), ('Dna', 'Dna')], default='Dl', max_length=5)),
                ('pers2_name', models.CharField(max_length=50)),
                ('inventar_number', models.PositiveBigIntegerField(verbose_name='Inventar')),
                ('object_description', models.CharField(max_length=256)),
                ('serian_number', models.CharField(max_length=25)),
                ('imei', models.CharField(max_length=25)),
            ],
        ),
    ]
