# Generated by Django 5.2.3 on 2025-07-16 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departament',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('departament_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='object_type',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='department_object',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('id_departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.departament')),
                ('id_object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.object_type')),
            ],
        ),
        migrations.CreateModel(
            name='inv_number_management_by_departmant_and_location',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('number_start', models.BigIntegerField(unique=True)),
                ('number_stop', models.BigIntegerField(unique=True)),
                ('id_departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.departament')),
                ('id_locatie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.location')),
            ],
        ),
        migrations.AddField(
            model_name='departament',
            name='id_locatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.location'),
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('can_create_pv', models.BooleanField(default=False)),
                ('id_departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.departament')),
            ],
        ),
        migrations.CreateModel(
            name='db_inventar',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('inv_number', models.PositiveBigIntegerField(unique=True)),
                ('object_description', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=75)),
                ('observations', models.CharField(max_length=256, null=True)),
                ('id_departament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.departament')),
                ('id_departamant_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.department_object')),
                ('id_locatie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.location')),
                ('id_persons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.person')),
            ],
        ),
        migrations.CreateModel(
            name='creat_pv',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('pv_type', models.CharField(max_length=10)),
                ('nr_ticket', models.CharField(max_length=10)),
                ('inv_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creare_pv.db_inventar')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pv_recipient', to='creare_pv.person')),
                ('reqester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pv_reqester', to='creare_pv.person')),
            ],
        ),
    ]
