# Generated by Django 5.2.3 on 2025-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creare_pv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryclasses',
            name='location',
        ),
        migrations.AlterField(
            model_name='assets',
            name='observations',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
